# Generated by Django 5.0.6 on 2024-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0002_coverphoto_profilephoto_timelinephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
