# Generated by Django 5.0.6 on 2024-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0004_alter_profilephoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploaderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
