# Generated by Django 5.0.6 on 2024-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0005_imageuploaderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploaderuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
