# Generated by Django 5.0.6 on 2024-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0006_imageuploaderuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploaderuser',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pictures/'),
        ),
        migrations.AddField(
            model_name='imageuploaderuser',
            name='cover_picture_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageuploaderuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='imageuploaderuser',
            name='profile_picture_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageuploaderuser',
            name='timeline_picture',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_pictures/'),
        ),
        migrations.AddField(
            model_name='imageuploaderuser',
            name='timeline_picture_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
