# Generated by Django 5.0.6 on 2024-09-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0007_imageuploaderuser_cover_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='cover_picture_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='profile_picture_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='timeline_picture',
        ),
        migrations.RemoveField(
            model_name='imageuploaderuser',
            name='timeline_picture_uploaded_at',
        ),
        migrations.CreateModel(
            name='CoverPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', models.ImageField(upload_to='cover_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_pictures', to='image_uploader_app.imageuploaderuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to='image_uploader_app.imageuploaderuser')),
            ],
        ),
        migrations.CreateModel(
            name='TimelinePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_picture', models.ImageField(upload_to='timeline_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_pictures', to='image_uploader_app.imageuploaderuser')),
            ],
        ),
    ]
