# Generated by Django 5.0.6 on 2024-10-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader_app', '0008_remove_imageuploaderuser_cover_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverPhoto',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
        migrations.DeleteModel(
            name='TimelinePhoto',
        ),
    ]
